services:
  - type: web
    name: searxng
    env: python
    buildCommand: |
      pip install pyyaml wheel setuptools<70
      pip install -r requirements.txt
    startCommand: gunicorn searx.webapp:app -b 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 8080
