use_default_settings: true

server:
  bind_address: "0.0.0.0"
  port: 8080
  cors: true
  cors_origins:
    - "*"
  public_instance: true
  secret_key: "a-random-secret"  # Optional

general:
  debug: false
